openapi: 3.0.3
info:
  title: API de MastersTavern
  version: 1.0.0
  description: API REST para gestionar la creación de personajes y la vinculación
    con los usuarios.
paths:
  /api/armors/:
    get:
      operationId: armors_retrieve
      tags:
      - armors
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/characters/:
    get:
      operationId: characters_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - characters
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCharacterList'
          description: ''
    post:
      operationId: characters_create
      tags:
      - characters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Character'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Character'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Character'
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
  /api/characters/{id}/:
    get:
      operationId: characters_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this characters.
        required: true
      tags:
      - characters
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
    put:
      operationId: characters_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this characters.
        required: true
      tags:
      - characters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Character'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Character'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Character'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
    patch:
      operationId: characters_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this characters.
        required: true
      tags:
      - characters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCharacter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCharacter'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCharacter'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
    delete:
      operationId: characters_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this characters.
        required: true
      tags:
      - characters
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/me/:
    get:
      operationId: me_retrieve
      tags:
      - me
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/weapons/:
    get:
      operationId: weapons_retrieve
      tags:
      - weapons
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    Character:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        weapons:
          type: array
          items:
            type: integer
        armor:
          type: integer
        avatar:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          maxLength: 100
        level:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        charClass:
          type: string
          maxLength: 100
        race:
          type: string
          maxLength: 100
        alignment:
          type: string
          maxLength: 100
        stats: {}
        STR:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        DEX:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        CON:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        INT:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        WIS:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        CHA:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        salvation: {}
        abilities: {}
        background:
          type: string
        feats:
          type: string
        inventory:
          type: string
        user:
          type: integer
          readOnly: true
      required:
      - id
      - user
    PaginatedCharacterList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Character'
    PatchedCharacter:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        weapons:
          type: array
          items:
            type: integer
        armor:
          type: integer
        avatar:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          maxLength: 100
        level:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        charClass:
          type: string
          maxLength: 100
        race:
          type: string
          maxLength: 100
        alignment:
          type: string
          maxLength: 100
        stats: {}
        STR:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        DEX:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        CON:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        INT:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        WIS:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        CHA:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
        salvation: {}
        abilities: {}
        background:
          type: string
        feats:
          type: string
        inventory:
          type: string
        user:
          type: integer
          readOnly: true
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
