# Generated by Django 6.0.4 on 2026-05-19 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('charClass', models.CharField(blank=True, max_length=100)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('alignment', models.CharField(blank=True, max_length=100)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('STR', models.IntegerField(blank=True, null=True)),
                ('DEX', models.IntegerField(blank=True, null=True)),
                ('CON', models.IntegerField(blank=True, null=True)),
                ('INT', models.IntegerField(blank=True, null=True)),
                ('WIS', models.IntegerField(blank=True, null=True)),
                ('CHA', models.IntegerField(blank=True, null=True)),
                ('salvation', models.JSONField(blank=True, default=list)),
                ('abilities', models.JSONField(blank=True, default=list)),
                ('background', models.TextField(blank=True)),
                ('feats', models.TextField(blank=True)),
                ('inventory', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
