# Generated by Django 6.0.4 on 2026-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_armors_characters_armor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armors',
            name='armor',
            field=models.IntegerField(),
        ),
    ]
