# Generated by Django 6.0.1 on 2026-01-22 09:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('system', models.CharField(choices=[('5E', '5e'), ('ONE', 'OneDnD'), ('CALL', 'Call of Cthulhu'), ('PATH', 'Pathfinder')], default='5E')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Campaings',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('race', models.CharField(max_length=25)),
                ('background', models.CharField(max_length=25)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('moral', models.CharField(choices=[('LAWFUL', 'Lawful'), ('NEUTRAL', 'Neutral'), ('CHAOTIC', 'Chaotic')], default='NEUTRAL')),
                ('goodness', models.CharField(choices=[('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('BAD', 'Bad')], default='NEUTRAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CharSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(blank=True, default=8)),
                ('dexterity', models.IntegerField(blank=True, default=8)),
                ('constitution', models.IntegerField(blank=True, default=8)),
                ('inteligence', models.IntegerField(blank=True, default=8)),
                ('wisdom', models.IntegerField(blank=True, default=8)),
                ('charisma', models.IntegerField(blank=True, default=8)),
                ('level', models.IntegerField(blank=True, default=1)),
                ('feats', models.TextField(blank=True, null=True)),
                ('inventory', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('pg', models.IntegerField(blank=True, default=0)),
                ('pg_e1', models.IntegerField(blank=True, null=True)),
                ('pg_e2', models.IntegerField(blank=True, null=True)),
                ('proficency', models.IntegerField(blank=True, default=0)),
                ('speed', models.IntegerField(blank=True, default=30)),
                ('atc_bonus', models.IntegerField(blank=True, default=1)),
                ('inspiration', models.BooleanField(default=False)),
                ('others_ca', models.IntegerField(blank=True, default=0)),
                ('others_iniciative', models.IntegerField(blank=True, default=0)),
                ('classdnd', models.CharField(choices=[('BARB', 'Barbarian'), ('BARD', 'Bard'), ('WARL', 'Warlock'), ('CLER', 'Cleric'), ('DRUID', 'Druid'), ('RANG', 'Ranger'), ('WARR', 'Warrior'), ('SPEL', 'Spellcaster'), ('MAGE', 'Mage'), ('PAL', 'Paladin'), ('MONK', 'Monk'), ('ROG', 'Rogue')], default='WARR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
            ],
            options={
                'verbose_name_plural': 'CharSheets',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ca', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
                ('extra', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy'), ('SHIELD', 'Shield')], default='LIGHT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.charsheet')),
            ],
            options={
                'verbose_name_plural': 'Armors',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaing')),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='users',
            field=models.ManyToManyField(to='core.user'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bonus', models.CharField(max_length=50)),
                ('extra', models.TextField(blank=True, null=True)),
                ('damage', models.CharField(choices=[('SLASH', 'Slashing'), ('BLUDGE', 'Bludgedning'), ('PIERCE', 'Piercing')], default='SLASH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.charsheet')),
            ],
            options={
                'verbose_name_plural': 'Weapons',
            },
        ),
    ]
